# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/singleline_vectorization',
                'doc_host': 'https://andrewlook.github.io',
                'git_url': 'https://github.com/andrewlook/singleline_vectorization',
                'lib_path': 'singleline_vectorization'},
  'syms': {'singleline_vectorization.core': {'singleline_vectorization.core.foo': ('core.html#foo', 'singleline_vectorization/core.py')}}}
