# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/singleline_vectorize',
                'doc_host': 'https://andrewlook.github.io',
                'git_url': 'https://github.com/andrewlook/singleline_vectorize',
                'lib_path': 'singleline_vectorize'},
  'syms': {'singleline_vectorize.core': {'singleline_vectorize.core.foo': ('core.html#foo', 'singleline_vectorize/core.py')}}}
